// ============================================================
// HP Field Estimator v2 — All 17 Phase Groups with Line Items
// ============================================================

import { PhaseGroup, LineItem, TierData } from './types';

// Helper to build a TierData set
function tiers(
  goodRate: number, goodName: string, goodDesc: string,
  betterRate: number, betterName: string, betterDesc: string,
  bestRate: number, bestName: string, bestDesc: string,
  photos?: { good?: string; better?: string; best?: string },
  specs?: { good?: string; better?: string; best?: string },
): { good: TierData; better: TierData; best: TierData } {
  return {
    good:   { rate: goodRate,   name: goodName,   desc: goodDesc,   photo: photos?.good,   specs: specs?.good },
    better: { rate: betterRate, name: betterName, desc: betterDesc, photo: photos?.better, specs: specs?.better },
    best:   { rate: bestRate,   name: bestName,   desc: bestDesc,   photo: photos?.best,   specs: specs?.best },
  };
}

// Helper to build a labor-only item (no material tiers)
function laborItem(
  id: string, name: string, shortName: string,
  unitType: LineItem['unitType'],
  hrsPerUnit: number, laborRate: number,
  salesDesc: string, sowTemplate: string,
  flagged = false, flagNote = '',
): LineItem {
  return {
    id, name, shortName, unitType,
    qty: 0, wastePct: 0,
    hasTiers: false,
    tier: 'good',
    tiers: tiers(0,'','', 0,'','', 0,'',''),
    laborMode: 'hr',
    laborRate,
    hrsPerUnit,
    flatRatePerUnit: 0,
    hasPaintPrep: false,
    paintPrep: 'none',
    paintRate: 0,
    flagged, flagNote,
    enabled: true,
    notes: '',
    salesDesc,
    sowTemplate,
    salesSelected: false,
    markupPct: null,
  };
}

// Helper to build a full material + labor item
function matItem(
  id: string, name: string, shortName: string,
  unitType: LineItem['unitType'],
  tierData: { good: TierData; better: TierData; best: TierData },
  hrsPerUnit: number, laborRate: number,
  salesDesc: string, sowTemplate: string,
  wastePct = 10,
  hasPaintPrep = false,
  flagged = false, flagNote = '',
): LineItem {
  return {
    id, name, shortName, unitType,
    qty: 0, wastePct,
    hasTiers: true,
    tier: 'good',
    tiers: tierData,
    laborMode: 'hr',
    laborRate,
    hrsPerUnit,
    flatRatePerUnit: 0,
    hasPaintPrep,
    paintPrep: 'none',
    paintRate: laborRate,
    flagged, flagNote,
    enabled: true,
    notes: '',
    salesDesc,
    sowTemplate,
    salesSelected: false,
    markupPct: null,
  };
}

// ─── DEFAULT RATES ────────────────────────────────────────────
const LABOR = 100;   // $/hr hard cost
const PAINT = 100;   // $/hr paint prep

// ─── PHASE 1: PRE-CONSTRUCTION ────────────────────────────────
const phase1: PhaseGroup = {
  id: 1, name: 'Pre-Construction', icon: '📋',
  description: 'Site assessment, permitting, material procurement, and subcontractor coordination before any work begins.',
  items: [
    laborItem('p1-site', 'Site Assessment / Measurements', 'Site assessment', 'hr', 1, LABOR,
      'Detailed site walk, measurements, and project scoping.',
      'Site assessment and measurements — {qty} hrs'),
    laborItem('p1-permit', 'Permit Pulling', 'Permit pulling', 'unit', 4, LABOR,
      'Permit application, submission, and coordination with the building department.',
      'Permit pulling — {qty} permit(s)'),
    laborItem('p1-material', 'Material Procurement / Lead Time Tracking', 'Material procurement', 'hr', 1, LABOR,
      'Sourcing materials, tracking lead times, and coordinating deliveries.',
      'Material procurement and scheduling — {qty} hrs'),
    laborItem('p1-sub', 'Subcontractor Scheduling', 'Sub scheduling', 'hr', 1, LABOR,
      'Coordinating subcontractor schedules and sequencing.',
      'Subcontractor scheduling — {qty} hrs'),
  ],
};

// ─── PHASE 2: DEMOLITION & ROUGH WORK ─────────────────────────
const phase2: PhaseGroup = {
  id: 2, name: 'Demo & Rough Work', icon: '🔨',
  description: 'Removal of existing materials, debris haul-away, and any hazardous material abatement required to prepare the space.',
  items: [
    matItem('p2-demo-int', 'Interior Demolition', 'Interior demo', 'sqft',
      tiers(0.50,'Standard demo','Walls, ceilings, flooring, fixtures', 0.75,'Selective demo','Careful removal preserving adjacent surfaces', 1.10,'Precision demo','Detailed selective demo, minimal disruption'),
      0.012, LABOR,
      'Removal of existing walls, ceilings, flooring, and fixtures.',
      'Interior demolition — {qty} sq ft', 0),
    matItem('p2-demo-ext', 'Exterior Demolition', 'Exterior demo', 'sqft',
      tiers(0.60,'Standard exterior demo','Siding, decking, fencing, roofing', 0.90,'Selective exterior demo','Careful removal', 1.25,'Precision exterior demo','Detailed selective removal'),
      0.015, LABOR,
      'Removal of existing siding, decking, fencing, or roofing.',
      'Exterior demolition — {qty} sq ft', 0),
    laborItem('p2-haul', 'Haul-Away / Dumpster', 'Debris haul-away', 'load', 3, LABOR,
      'Debris removal and dumpster service.',
      'Debris haul-away — {qty} load(s)'),
    laborItem('p2-hazmat', 'Asbestos / Hazmat Testing & Abatement', 'Hazmat abatement', 'unit', 8, LABOR,
      'Testing and abatement of hazardous materials.',
      'Hazmat testing/abatement — {qty} area(s)', true, 'Sub specialty — licensed abatement contractor required'),
    laborItem('p2-struct', 'Structural Work (Beams, Posts, Headers)', 'Structural work', 'unit', 8, LABOR,
      'Beam work, post replacement, and header installation.',
      'Structural work — {qty} location(s)', true, 'Engineer review required'),
  ],
};

// ─── PHASE 3: MECHANICAL ROUGH-IN ─────────────────────────────
const phase3: PhaseGroup = {
  id: 3, name: 'Mechanical Rough-In', icon: '🔧',
  description: 'Rough-in of plumbing, electrical, HVAC, and gas lines before walls are closed — all work performed by licensed contractors.',
  items: [
    laborItem('p3-plumb', 'Plumbing Rough-In', 'Plumbing rough-in', 'fixture', 4, LABOR,
      'Supply lines, DWV, and new drain locations.',
      'Plumbing rough-in — {qty} fixture(s)', true, 'Licensed plumber required'),
    laborItem('p3-elec', 'Electrical Rough-In', 'Electrical rough-in', 'circuit', 3, LABOR,
      'Panel work, new circuits, and rough wire.',
      'Electrical rough-in — {qty} circuit(s)', true, 'Licensed electrician required'),
    laborItem('p3-hvac', 'HVAC Rough-In', 'HVAC rough-in', 'unit', 8, LABOR,
      'Duct work, new runs, and equipment sizing.',
      'HVAC rough-in — {qty} unit(s)', true, 'Licensed HVAC contractor required'),
    laborItem('p3-gas', 'Gas Lines', 'Gas lines', 'unit', 4, LABOR,
      'New gas runs and appliance stubs.',
      'Gas line work — {qty} location(s)', true, 'Licensed gas contractor required'),
  ],
};

// ─── PHASE 4: INSULATION & WEATHERPROOFING ────────────────────
const phase4: PhaseGroup = {
  id: 4, name: 'Insulation & Weatherproofing', icon: '🏠',
  description: 'Insulation installation and weather barrier application to improve energy efficiency, comfort, and moisture protection.',
  items: [
    matItem('p4-batt', 'Batt Insulation', 'Batt insulation', 'sqft',
      tiers(0.45,'R-13 fiberglass batt','Standard wall insulation', 0.70,'R-19 fiberglass batt','Upgraded wall/ceiling insulation', 1.10,'R-21 mineral wool','Premium sound + thermal insulation'),
      0.004, LABOR,
      'Fiberglass or mineral wool batt insulation for walls and ceilings.',
      'Batt insulation — {qty} sq ft', 5),
    matItem('p4-foam', 'Spray Foam Insulation', 'Spray foam', 'sqft',
      tiers(1.20,'Open-cell spray foam','Air sealing, rim joist', 2.00,'Closed-cell spray foam','Superior moisture barrier', 3.00,'2-lb closed-cell foam','Maximum R-value per inch'),
      0.005, LABOR,
      'Spray foam insulation for rim joists and air sealing.',
      'Spray foam insulation — {qty} sq ft', 5),
    matItem('p4-wrap', 'House Wrap / Weather Barrier', 'House wrap', 'sqft',
      tiers(0.18,'Standard house wrap','Tyvek HomeWrap', 0.28,'Premium house wrap','Tyvek DrainWrap', 0.45,'Fluid-applied WRB','Superior air/water barrier'),
      0.003, LABOR,
      'Exterior weather barrier installation.',
      'House wrap / weather barrier — {qty} sq ft', 10),
    matItem('p4-vapor', 'Vapor Barrier (Crawl Space)', 'Vapor barrier', 'sqft',
      tiers(0.15,'6-mil poly','Standard crawl space vapor barrier', 0.25,'10-mil poly','Heavy-duty vapor barrier', 0.45,'20-mil reinforced','Commercial-grade encapsulation'),
      0.003, LABOR,
      'Crawl space vapor barrier installation.',
      'Vapor barrier — {qty} sq ft', 5),
  ],
};

// ─── PHASE 5: DRYWALL ─────────────────────────────────────────
const phase5: PhaseGroup = {
  id: 5, name: 'Drywall', icon: '🧱',
  description: 'Drywall installation, taping, mudding, and finishing to the specified level — ready for paint or texture.',
  items: [
    matItem('p5-hang', 'Hang Drywall', 'Drywall hang', 'sqft',
      tiers(0.35,'1/2" standard drywall','Walls and ceilings', 0.45,'5/8" Type X drywall','Fire-rated, ceilings', 0.65,'5/8" soundboard','Sound-dampening drywall'),
      0.006, LABOR,
      'Drywall installation on walls and ceilings.',
      'Drywall hang — {qty} sq ft', 10),
    matItem('p5-tape', 'Tape, Mud & Finish', 'Tape & mud', 'sqft',
      tiers(0.55,'Level 3 finish','Standard residential finish', 0.80,'Level 4 finish','Smooth, ready for flat paint', 1.20,'Level 5 finish','Skim coat, premium smooth finish'),
      0.010, LABOR,
      'Taping, mudding, and finishing drywall to specified level.',
      'Tape, mud & finish — {qty} sq ft (Level {tier})', 0),
    matItem('p5-texture', 'Texture', 'Drywall texture', 'sqft',
      tiers(0.30,'Knockdown texture','Standard spray knockdown', 0.40,'Orange peel texture','Fine spray texture', 0.65,'Skip trowel texture','Hand-applied artisan texture'),
      0.005, LABOR,
      'Spray or hand-applied texture to match existing or new finish.',
      'Drywall texture — {qty} sq ft', 0),
    matItem('p5-repair', 'Drywall Repair / Patch', 'Drywall repair', 'patch',
      tiers(45,'Small patch repair','Up to 6" patch', 85,'Medium patch repair','6"–12" patch', 150,'Large patch repair','12"+ patch, full float'),
      0.75, LABOR,
      'Patching and repairing existing drywall.',
      'Drywall repair — {qty} patch(es)', 0),
  ],
};

// ─── PHASE 6: FLOORING ────────────────────────────────────────
const phase6: PhaseGroup = {
  id: 6, name: 'Flooring', icon: '🪵',
  description: 'Flooring supply and installation including subfloor preparation, material installation, transitions, and cleanup.',
  items: [
    matItem('p6-subfloor', 'Subfloor Prep', 'Subfloor prep', 'sqft',
      tiers(0.40,'Basic leveling','Self-leveler, minor repairs', 0.75,'Subfloor repair','Sheathing replacement, sistering', 1.20,'Full subfloor replacement','New 3/4" T&G sheathing'),
      0.008, LABOR,
      'Subfloor leveling, repair, or replacement.',
      'Subfloor prep — {qty} sq ft', 0),
    matItem('p6-lvp', 'LVP / LVT Flooring', 'LVP flooring', 'sqft',
      tiers(2.20,'Good LVP — 4mm','Entry-level luxury vinyl plank', 3.50,'Better LVP — 6mm','Mid-grade with attached underlayment', 5.50,'Best LVP — 8mm','Commercial-grade, waterproof core'),
      0.012, LABOR,
      'Luxury vinyl plank or tile flooring — waterproof, durable, and stylish.',
      'LVP flooring — {qty} sq ft ({tier} grade)', 12),
    matItem('p6-tile', 'Tile Flooring', 'Floor tile', 'sqft',
      tiers(2.50,'Ceramic tile 12×12','Standard floor tile', 4.00,'Porcelain tile 12×24','Premium porcelain', 7.00,'Large format tile 24×24','Designer large format'),
      0.020, LABOR,
      'Ceramic or porcelain floor tile with backer and grout.',
      'Floor tile — {qty} sq ft ({tier} grade)', 15),
    matItem('p6-hardwood', 'Hardwood Flooring', 'Hardwood', 'sqft',
      tiers(4.50,'Engineered hardwood 3/8"','Floating or glue-down', 6.50,'Solid hardwood 3/4"','Nail-down, can be refinished', 9.00,'Wide-plank hardwood 5"','Premium wide-plank solid'),
      0.018, LABOR,
      'Hardwood flooring — nail-down or glue-down installation.',
      'Hardwood flooring — {qty} sq ft ({tier} grade)', 12),
    matItem('p6-carpet', 'Carpet', 'Carpet', 'sqft',
      tiers(1.80,'Builder-grade carpet','Standard residential carpet + pad', 3.00,'Mid-grade carpet','Better texture and durability', 5.00,'Premium carpet','Plush or patterned, thick pad'),
      0.010, LABOR,
      'Carpet with pad — supply and installation.',
      'Carpet — {qty} sq ft ({tier} grade)', 10),
    matItem('p6-trans', 'Transitions & Thresholds', 'Transitions', 'unit',
      tiers(12,'Standard transition strip','T-molding or reducer', 22,'Hardwood transition','Matching wood threshold', 38,'Custom threshold','Solid wood or metal custom'),
      0.25, LABOR,
      'Transition strips and thresholds between flooring types.',
      'Transitions/thresholds — {qty} piece(s)', 0),
    matItem('p6-demo', 'Floor Demo / Removal', 'Floor removal', 'sqft',
      tiers(0.30,'Standard floor removal','Carpet, vinyl, LVP', 0.50,'Tile floor removal','Ceramic/porcelain removal', 0.80,'Hardwood removal','Nail-down hardwood removal'),
      0.008, LABOR,
      'Removal of existing flooring.',
      'Floor removal — {qty} sq ft', 0),
  ],
};

// ─── PHASE 7: TILE WORK ───────────────────────────────────────
const phase7: PhaseGroup = {
  id: 7, name: 'Tile Work', icon: '🚿',
  description: 'Tile supply and installation for showers, tub surrounds, backsplashes, and feature walls — including waterproofing, grouting, and sealing.',
  items: [
    matItem('p7-shower', 'Shower Wall Tile', 'Shower tile', 'sqft',
      tiers(3.50,'Ceramic subway tile','3×6 classic subway', 5.50,'Porcelain wall tile','12×24 porcelain', 9.00,'Natural stone tile','Marble, travertine, or slate'),
      0.025, LABOR,
      'Shower wall tile — supply and installation including waterproofing.',
      'Shower wall tile — {qty} sq ft ({tier} grade)', 15),
    matItem('p7-tub', 'Tub Surround Tile', 'Tub surround', 'sqft',
      tiers(3.00,'Ceramic subway tile','3×6 classic subway', 4.50,'Porcelain wall tile','12×24 porcelain', 8.00,'Natural stone tile','Marble or travertine'),
      0.022, LABOR,
      'Tub surround tile — supply and installation.',
      'Tub surround tile — {qty} sq ft ({tier} grade)', 15),
    matItem('p7-backsplash', 'Backsplash Tile', 'Backsplash', 'sqft',
      tiers(4.00,'Ceramic subway tile','3×6 or 4×4 ceramic', 7.00,'Glass mosaic tile','Glass or mixed mosaic', 12.00,'Natural stone mosaic','Marble or travertine mosaic'),
      0.030, LABOR,
      'Kitchen or bath backsplash tile — supply and installation.',
      'Backsplash tile — {qty} sq ft ({tier} grade)', 10),
    matItem('p7-feature', 'Feature Wall / Fireplace Tile', 'Feature wall tile', 'sqft',
      tiers(5.00,'Ceramic feature tile','Decorative ceramic', 9.00,'Porcelain feature tile','Large format porcelain', 15.00,'Natural stone feature','Ledger stone or marble'),
      0.035, LABOR,
      'Decorative feature wall or fireplace tile.',
      'Feature wall tile — {qty} sq ft ({tier} grade)', 10),
    matItem('p7-waterproof', 'Waterproofing / Membrane', 'Waterproofing', 'sqft',
      tiers(0.80,'Liquid waterproofing','Redgard or similar', 1.20,'Sheet membrane','Schluter Kerdi or similar', 1.80,'Full system waterproofing','Schluter system + corners'),
      0.006, LABOR,
      'Waterproofing membrane for wet areas.',
      'Waterproofing membrane — {qty} sq ft', 10),
    laborItem('p7-grout', 'Grout, Caulk & Sealing', 'Grout & caulk', 'sqft', 0.004, LABOR,
      'Grouting all tile joints, caulking transitions, and sealing.',
      'Grout, caulk & sealing — {qty} sq ft'),
  ],
};

// ─── PHASE 8: FRAMING & CARPENTRY ─────────────────────────────
const phase8: PhaseGroup = {
  id: 8, name: 'Framing & Carpentry', icon: '🪚',
  description: 'Structural framing for new walls, ceilings, openings, and subfloor repairs — the backbone of any remodel.',
  items: [
    matItem('p8-wall', 'New Wall Framing', 'Wall framing', 'lf',
      tiers(4.50,'2×4 stud wall','Standard interior partition', 6.00,'2×6 stud wall','Exterior or plumbing wall', 8.50,'Steel stud framing','Commercial-grade metal framing'),
      0.08, LABOR,
      'New interior partition wall framing.',
      'Wall framing — {qty} lf', 10),
    matItem('p8-ceiling', 'Ceiling Framing', 'Ceiling framing', 'sqft',
      tiers(2.50,'Simple soffit','Basic drop or soffit', 4.00,'Tray ceiling framing','Stepped tray ceiling', 6.50,'Coffered ceiling','Full coffered framing'),
      0.015, LABOR,
      'Soffit, drop, or tray ceiling framing.',
      'Ceiling framing — {qty} sq ft', 10),
    laborItem('p8-block', 'Blocking (Grab Bars, TV, Cabinets)', 'Blocking', 'unit', 1.5, LABOR,
      'Structural backing for grab bars, TV mounts, and cabinets.',
      'Blocking — {qty} location(s)'),
    matItem('p8-joist', 'Subfloor Framing Repair', 'Joist repair', 'lf',
      tiers(8,'Joist sistering','Sister existing joists', 14,'Rim joist repair','Rim joist replacement', 22,'Full joist replacement','New joist installation'),
      0.12, LABOR,
      'Joist sistering, rim joist, and subfloor framing repair.',
      'Subfloor framing repair — {qty} lf', 5),
    laborItem('p8-opening', 'Exterior Framing (New Openings)', 'New openings', 'opening', 6, LABOR,
      'New window or door openings with headers.',
      'New exterior openings — {qty} opening(s)', true, 'Structural review recommended'),
  ],
};

// ─── PHASE 9: EXTERIOR WORK ───────────────────────────────────
const phase9: PhaseGroup = {
  id: 9, name: 'Exterior Work', icon: '🏡',
  description: 'Exterior improvements including siding, roofing, gutters, decks, fencing, and concrete flatwork.',
  items: [
    matItem('p9-siding', 'Siding Installation', 'Siding', 'sqft',
      tiers(2.50,'LP SmartSide lap','Engineered wood lap siding', 3.80,'Fiber cement (HardiePlank)','James Hardie lap siding', 6.00,'Cedar siding','Natural wood siding'),
      0.015, LABOR,
      'New siding installation — lap, shingle, board & batten, or T1-11.',
      'Siding installation — {qty} sq ft ({tier} grade)', 10),
    matItem('p9-siding-paint', 'Siding Paint / Stain', 'Siding paint', 'sqft',
      tiers(0.25,'1-coat exterior paint','Primer + 1 finish coat', 0.40,'2-coat exterior paint','Primer + 2 finish coats', 0.65,'Solid stain','Premium solid stain system'),
      0.006, LABOR,
      'Exterior siding paint or stain.',
      'Siding paint/stain — {qty} sq ft', 0, true),
    matItem('p9-soffit', 'Soffit & Fascia', 'Soffit & fascia', 'lf',
      tiers(4.50,'Vinyl soffit & fascia','Standard vinyl', 7.00,'Aluminum soffit & fascia','Commercial aluminum', 10.00,'Cedar soffit & fascia','Natural wood'),
      0.06, LABOR,
      'Soffit and fascia replacement or repainting.',
      'Soffit & fascia — {qty} lf', 10),
    matItem('p9-gutter', 'Gutters', 'Gutters', 'lf',
      tiers(3.50,'5" aluminum gutters','Standard K-style aluminum', 5.00,'6" aluminum gutters','Oversized K-style', 8.00,'Copper gutters','Premium copper gutters'),
      0.04, LABOR,
      'Gutter installation or replacement.',
      'Gutters — {qty} lf', 5),
    laborItem('p9-roof', 'Roofing', 'Roofing', 'sqft', 0.008, LABOR,
      'Shingle, flat, or metal roofing.',
      'Roofing — {qty} sq ft', true, 'Sub specialty — roofing contractor required'),
    matItem('p9-deck', 'Deck — New Build', 'New deck', 'sqft',
      tiers(12,'Pressure-treated deck','PT framing + decking', 18,'Composite deck','Trex or similar composite', 28,'Hardwood deck','Ipe or cedar decking'),
      0.025, LABOR,
      'New deck construction — framing and decking.',
      'New deck — {qty} sq ft ({tier} grade)', 10),
    matItem('p9-deck-repair', 'Deck Refinish / Repair', 'Deck repair', 'sqft',
      tiers(1.50,'Deck clean & seal','Power wash + sealer', 3.00,'Deck refinish','Sand, stain, and seal', 6.00,'Board replacement','Replace damaged boards'),
      0.010, LABOR,
      'Deck refinishing, repair, or board replacement.',
      'Deck refinish/repair — {qty} sq ft', 0),
    matItem('p9-fence', 'Fence — New Install', 'New fence', 'lf',
      tiers(18,'Dog-ear cedar fence','6\' dog-ear cedar', 28,'Shadowbox cedar fence','Shadowbox style', 45,'Cedar privacy fence','Custom cedar privacy'),
      0.06, LABOR,
      'New fence installation.',
      'New fence — {qty} lf ({tier} grade)', 5),
    matItem('p9-fence-repair', 'Fence Repair', 'Fence repair', 'unit',
      tiers(35,'Post reset / board replace','Standard repair', 65,'Section rebuild','Rebuild damaged section', 120,'Full panel replacement','Replace full fence panel'),
      1.5, LABOR,
      'Fence repair — post reset, board replacement, or section rebuild.',
      'Fence repair — {qty} repair(s)', 0),
    matItem('p9-concrete', 'Concrete / Flatwork', 'Concrete', 'sqft',
      tiers(6,'Standard broom finish','Driveway, walkway, patio', 9,'Exposed aggregate','Decorative exposed aggregate', 14,'Stamped concrete','Stamped pattern concrete'),
      0.015, LABOR,
      'Concrete flatwork — driveway, walkway, or patio.',
      'Concrete/flatwork — {qty} sq ft ({tier} grade)', 5),
    laborItem('p9-landscape', 'Landscaping / Cleanup', 'Landscaping', 'hr', 1, LABOR,
      'Landscaping, grading, and site cleanup.',
      'Landscaping/cleanup — {qty} hrs'),
  ],
};

// ─── PHASE 10: DOORS & WINDOWS ────────────────────────────────
const phase10: PhaseGroup = {
  id: 10, name: 'Doors & Windows', icon: '🚪',
  description: 'Interior and exterior door and window installation, including hardware, weatherstripping, and exterior trim.',
  items: [
    matItem('p10-int-door', 'Interior Doors', 'Interior doors', 'door',
      tiers(120,'Hollow-core prehung','Standard hollow-core', 220,'Solid-core prehung','Solid-core 1-3/4"', 380,'Solid wood prehung','Knotty alder or pine'),
      1.5, LABOR,
      'Interior prehung or slab door installation.',
      'Interior doors — {qty} door(s) ({tier} grade)', 0),
    matItem('p10-ext-door', 'Exterior Doors', 'Exterior doors', 'door',
      tiers(280,'Fiberglass entry door','Standard fiberglass prehung', 480,'Steel entry door','Heavy-duty steel prehung', 750,'Wood entry door','Solid wood entry door'),
      2.5, LABOR,
      'Exterior prehung door with weatherstripping and threshold.',
      'Exterior doors — {qty} door(s) ({tier} grade)', 0),
    matItem('p10-pocket', 'Sliding / Pocket Doors', 'Pocket doors', 'door',
      tiers(180,'Hollow-core pocket','Standard pocket door kit', 320,'Solid-core pocket','Solid-core pocket door', 550,'Barn door','Sliding barn door hardware + door'),
      3, LABOR,
      'Sliding or pocket door installation.',
      'Sliding/pocket doors — {qty} door(s) ({tier} grade)', 0),
    matItem('p10-window', 'Window Replacement', 'Windows', 'window',
      tiers(280,'Vinyl double-pane','Standard vinyl replacement', 420,'Fiberglass window','Premium fiberglass', 680,'Wood-clad window','Wood-clad interior/exterior'),
      2.5, LABOR,
      'Window replacement — vinyl, fiberglass, or wood-clad.',
      'Window replacement — {qty} window(s) ({tier} grade)', 0),
    matItem('p10-win-trim', 'Window Trim — Exterior', 'Exterior window trim', 'window',
      tiers(45,'PVC exterior trim','Low-maintenance PVC', 70,'Fiber cement trim','James Hardie trim', 110,'Cedar exterior trim','Natural cedar trim'),
      1.5, LABOR,
      'Exterior window trim installation.',
      'Exterior window trim — {qty} window(s)', 10),
    matItem('p10-hardware', 'Door Hardware', 'Door hardware', 'door',
      tiers(35,'Builder-grade hardware','Kwikset or similar', 75,'Mid-grade hardware','Schlage or similar', 150,'Premium hardware','Baldwin or Emtek'),
      0.5, LABOR,
      'Door knobs, levers, and deadbolts.',
      'Door hardware — {qty} door(s) ({tier} grade)', 0),
    laborItem('p10-garage', 'Garage Door Install / Replace', 'Garage door', 'door', 4, LABOR,
      'Garage door installation or replacement.',
      'Garage door — {qty} door(s)', true, 'Sub specialty — garage door contractor recommended'),
  ],
};

// ─── PHASE 11: TRIM & FINISH CARPENTRY ────────────────────────
const phase11: PhaseGroup = {
  id: 11, name: 'Trim & Finish Carpentry', icon: '📐',
  description: 'Finish carpentry including baseboard, door and window casing, crown molding, wainscoting, built-ins, and stair work — the details that make a home feel finished.',
  items: [
    matItem('p11-bb', 'Baseboard', 'Baseboard', 'lf',
      tiers(0.68,'Finger-joint pine, primed','Colonial 3.5" — paint-grade', 1.05,'MDF colonial base, primed','Colonial 4.25" — smooth MDF', 1.95,'Solid poplar, unfinished','Colonial 4.25" — stain-grade'),
      0.04, LABOR,
      'Baseboard installation — colonial, ranch, craftsman, or farmhouse profiles.',
      'Baseboard — {qty} lf ({tier} grade)', 10, true),
    matItem('p11-dc', 'Door Casing', 'Door casing', 'opening',
      tiers(0.72,'Finger-joint pine, primed','Colonial 2.5" — paint-grade', 1.10,'MDF colonial casing, primed','Colonial 3.5" — smooth MDF', 2.20,'Solid poplar, unfinished','Colonial 3.5" — stain-grade'),
      1.5, LABOR,
      'Door casing installation — colonial or craftsman profiles.',
      'Door casing — {qty} opening(s) ({tier} grade)', 10, true),
    matItem('p11-wc', 'Window Casing', 'Window casing', 'window',
      tiers(0.72,'Finger-joint pine, primed','Colonial 2.5" — paint-grade', 1.10,'MDF colonial casing, primed','Colonial 3.5" — smooth MDF', 2.20,'Solid poplar, unfinished','Colonial 3.5" — stain-grade'),
      1.5, LABOR,
      'Window casing installation — colonial or craftsman profiles.',
      'Window casing — {qty} window(s) ({tier} grade)', 10, true),
    matItem('p11-crown', 'Crown Molding', 'Crown molding', 'lf',
      tiers(1.20,'Finger-joint pine crown','3.5" colonial crown — paint-grade', 1.80,'MDF crown molding','4.5" MDF — smooth finish', 3.20,'Solid poplar crown','5.5" solid — stain-grade'),
      0.06, LABOR,
      'Crown molding installation.',
      'Crown molding — {qty} lf ({tier} grade)', 15, true),
    matItem('p11-chair', 'Chair Rail', 'Chair rail', 'lf',
      tiers(0.55,'Finger-joint pine','2.5" chair rail — paint-grade', 0.85,'MDF chair rail','3" MDF — smooth finish', 1.50,'Solid poplar','3" solid — stain-grade'),
      0.04, LABOR,
      'Chair rail installation.',
      'Chair rail — {qty} lf ({tier} grade)', 10, true),
    matItem('p11-wains', 'Wainscoting / Board & Batten', 'Wainscoting', 'sqft',
      tiers(2.50,'MDF board & batten','Standard board & batten', 3.80,'Beadboard wainscoting','Classic beadboard panels', 5.50,'Solid wood wainscoting','Raised panel solid wood'),
      0.018, LABOR,
      'Wainscoting or board and batten installation.',
      'Wainscoting/board & batten — {qty} sq ft ({tier} grade)', 10, true),
    matItem('p11-shelf', 'Built-In Shelving', 'Built-in shelving', 'lf',
      tiers(35,'Melamine shelving','Standard melamine built-ins', 65,'Plywood shelving','Paint-grade plywood built-ins', 110,'Solid wood built-ins','Solid wood custom built-ins'),
      0.5, LABOR,
      'Built-in shelving installation.',
      'Built-in shelving — {qty} lf ({tier} grade)', 5),
    matItem('p11-stair', 'Stair Treads & Risers', 'Stair treads', 'step',
      tiers(45,'Pine treads & risers','Paint-grade pine', 85,'Oak treads, pine risers','Stain-grade oak treads', 150,'Solid oak treads & risers','Full stain-grade oak'),
      1.5, LABOR,
      'Stair tread and riser installation.',
      'Stair treads & risers — {qty} step(s) ({tier} grade)', 5),
    matItem('p11-rail', 'Handrail & Balusters', 'Handrail', 'lf',
      tiers(18,'Pine handrail + wood balusters','Standard wood', 32,'Oak handrail + wood balusters','Stain-grade oak', 55,'Oak handrail + metal balusters','Premium iron balusters'),
      0.12, LABOR,
      'Handrail and baluster installation.',
      'Handrail & balusters — {qty} lf ({tier} grade)', 10),
    matItem('p11-mantel', 'Fireplace Mantel', 'Fireplace mantel', 'unit',
      tiers(280,'MDF mantel surround','Paint-grade MDF mantel', 480,'Poplar mantel surround','Stain-grade poplar', 850,'Custom wood mantel','Custom built solid wood mantel'),
      6, LABOR,
      'Fireplace mantel installation.',
      'Fireplace mantel — {qty} unit(s) ({tier} grade)', 0),
    matItem('p11-closet', 'Closet Systems', 'Closet systems', 'closet',
      tiers(180,'Wire shelving system','ClosetMaid wire system', 380,'Melamine closet system','Modular melamine system', 750,'Custom closet system','Custom built-in closet'),
      4, LABOR,
      'Closet organization system installation.',
      'Closet systems — {qty} closet(s) ({tier} grade)', 0),
    laborItem('p11-attic', 'Attic Access / Pull-Down Stair', 'Attic access', 'unit', 3, LABOR,
      'Attic access hatch or pull-down stair installation.',
      'Attic access/pull-down stair — {qty} unit(s)'),
  ],
};

// ─── PHASE 12: CABINETRY & COUNTERTOPS ────────────────────────
const phase12: PhaseGroup = {
  id: 12, name: 'Cabinetry & Countertops', icon: '🍳',
  description: 'Kitchen and bathroom cabinetry, countertops, and hardware — supply and installation.',
  items: [
    matItem('p12-cab', 'Kitchen Cabinets', 'Kitchen cabinets', 'lf',
      tiers(180,'Stock cabinets','Home Depot/Lowe\'s stock', 320,'Semi-custom cabinets','IKEA or semi-custom', 580,'Custom cabinets','Full custom cabinetry'),
      1.5, LABOR,
      'Kitchen cabinet supply and installation — base and upper.',
      'Kitchen cabinets — {qty} lf ({tier} grade)', 5),
    matItem('p12-vanity', 'Bathroom Vanity', 'Bathroom vanity', 'unit',
      tiers(280,'Stock vanity','Standard stock vanity', 480,'Semi-custom vanity','Upgraded semi-custom', 850,'Custom vanity','Custom built vanity'),
      3, LABOR,
      'Bathroom vanity supply and installation.',
      'Bathroom vanity — {qty} unit(s) ({tier} grade)', 0),
    matItem('p12-counter', 'Countertops', 'Countertops', 'sqft',
      tiers(18,'Laminate countertop','Formica or similar', 55,'Quartz countertop','Engineered quartz', 85,'Granite countertop','Natural granite slab'),
      0.025, LABOR,
      'Countertop supply and installation.',
      'Countertops — {qty} sq ft ({tier} grade)', 5),
    matItem('p12-hardware', 'Cabinet Hardware', 'Cabinet hardware', 'unit',
      tiers(4,'Builder-grade pulls','Basic bar pulls', 12,'Mid-grade hardware','Brushed nickel or matte black', 28,'Premium hardware','Emtek or similar'),
      0.15, LABOR,
      'Cabinet pulls, knobs, and hinges.',
      'Cabinet hardware — {qty} piece(s) ({tier} grade)', 0),
    matItem('p12-shelf', 'Shelving (Pantry / Laundry)', 'Pantry shelving', 'lf',
      tiers(12,'Wire shelving','Standard wire shelving', 22,'Melamine shelving','Melamine fixed shelving', 38,'Solid wood shelving','Solid wood pantry shelving'),
      0.3, LABOR,
      'Pantry or laundry room shelving.',
      'Pantry/laundry shelving — {qty} lf ({tier} grade)', 5),
  ],
};

// ─── PHASE 13: PLUMBING FINISH ────────────────────────────────
const phase13: PhaseGroup = {
  id: 13, name: 'Plumbing Finish', icon: '🚰',
  description: 'Plumbing fixture installation including faucets, sinks, toilets, tubs, shower systems, and appliance hookups.',
  items: [
    matItem('p13-faucet', 'Fixture Swap (Faucet / Showerhead)', 'Fixture swap', 'fixture',
      tiers(80,'Builder-grade fixture','Standard chrome fixture', 180,'Mid-grade fixture','Brushed nickel or matte black', 380,'Premium fixture','Kohler, Moen, or Delta premium'),
      1.5, LABOR,
      'Faucet, showerhead, or hose bib replacement.',
      'Fixture swap — {qty} fixture(s) ({tier} grade)', 0),
    matItem('p13-toilet', 'Toilet Supply & Install', 'Toilet', 'unit',
      tiers(180,'Standard toilet','Elongated 2-piece toilet', 320,'Comfort height toilet','ADA comfort height', 550,'Wall-hung toilet','Wall-mounted toilet'),
      2, LABOR,
      'Toilet supply and installation.',
      'Toilet — {qty} unit(s) ({tier} grade)', 0),
    matItem('p13-sink', 'Sink Supply & Install', 'Sink', 'unit',
      tiers(120,'Drop-in sink','Standard drop-in basin', 220,'Undermount sink','Undermount stainless or porcelain', 420,'Farmhouse sink','Apron-front farmhouse sink'),
      2, LABOR,
      'Sink supply and installation.',
      'Sink — {qty} unit(s) ({tier} grade)', 0),
    matItem('p13-tub', 'Tub Supply & Install', 'Tub', 'unit',
      tiers(380,'Alcove tub','Standard 60" alcove tub', 680,'Freestanding tub','Freestanding soaking tub', 1200,'Jetted tub','Jetted or air tub'),
      4, LABOR,
      'Bathtub supply and installation.',
      'Tub — {qty} unit(s) ({tier} grade)', 0),
    matItem('p13-shower', 'Shower System (Valve, Head, Trim)', 'Shower system', 'unit',
      tiers(180,'Standard shower valve','Pressure-balance valve + head', 380,'Thermostatic valve','Thermostatic shower system', 750,'Multi-function system','Rain head + handheld + body sprays'),
      3, LABOR,
      'Shower valve, head, and trim kit.',
      'Shower system — {qty} unit(s) ({tier} grade)', 0),
    laborItem('p13-wh', 'Water Heater Replacement', 'Water heater', 'unit', 4, LABOR,
      'Water heater replacement.',
      'Water heater — {qty} unit(s)', true, 'Licensed plumber required'),
    laborItem('p13-dw', 'Dishwasher Hookup', 'Dishwasher hookup', 'unit', 1.5, LABOR,
      'Dishwasher hookup and installation.',
      'Dishwasher hookup — {qty} unit(s)'),
    laborItem('p13-disp', 'Garbage Disposal', 'Garbage disposal', 'unit', 1.5, LABOR,
      'Garbage disposal installation.',
      'Garbage disposal — {qty} unit(s)'),
    laborItem('p13-washer', 'Washer Hookup', 'Washer hookup', 'unit', 1, LABOR,
      'Washer supply and drain hookup.',
      'Washer hookup — {qty} unit(s)'),
  ],
};

// ─── PHASE 14: ELECTRICAL FINISH ──────────────────────────────
const phase14: PhaseGroup = {
  id: 14, name: 'Electrical Finish', icon: '💡',
  description: 'Electrical finish work including light fixtures, ceiling fans, outlets, recessed lighting, and smart devices.',
  items: [
    matItem('p14-light', 'Light Fixture Swap', 'Light fixtures', 'fixture',
      tiers(45,'Builder-grade fixture','Standard light fixture', 120,'Mid-grade fixture','Brushed nickel or matte black', 280,'Designer fixture','Premium designer fixture'),
      0.75, LABOR,
      'Light fixture replacement.',
      'Light fixtures — {qty} fixture(s) ({tier} grade)', 0),
    matItem('p14-fan', 'Ceiling Fan Install', 'Ceiling fans', 'fan',
      tiers(80,'Builder-grade fan','Standard ceiling fan', 180,'Mid-grade fan','Remote-control fan', 380,'Premium fan','Hunter or Minka premium fan'),
      1.5, LABOR,
      'Ceiling fan installation.',
      'Ceiling fans — {qty} fan(s) ({tier} grade)', 0),
    laborItem('p14-outlet', 'Outlet / Switch Replacement', 'Outlets/switches', 'device', 0.5, LABOR,
      'Outlet and switch replacement.',
      'Outlets/switches — {qty} device(s)'),
    laborItem('p14-gfci', 'GFCI Outlet Install', 'GFCI outlets', 'device', 0.75, LABOR,
      'GFCI outlet installation.',
      'GFCI outlets — {qty} outlet(s)'),
    matItem('p14-undercab', 'Under-Cabinet Lighting', 'Under-cabinet lighting', 'lf',
      tiers(12,'Plug-in LED strip','Basic LED strip', 22,'Hardwired LED strip','Hardwired LED system', 38,'Premium LED system','Kichler or similar premium'),
      0.3, LABOR,
      'Under-cabinet lighting installation.',
      'Under-cabinet lighting — {qty} lf ({tier} grade)', 5),
    matItem('p14-can', 'Recessed Can Lights', 'Recessed lights', 'can',
      tiers(18,'Standard 6" can','Basic recessed can', 32,'LED retrofit can','Integrated LED can', 55,'Premium LED can','Halo or Lutron premium'),
      1, LABOR,
      'Recessed can light installation.',
      'Recessed lights — {qty} can(s) ({tier} grade)', 0),
    laborItem('p14-exhaust', 'Exhaust Fan (Bath)', 'Exhaust fans', 'fan', 1.5, LABOR,
      'Bathroom exhaust fan installation.',
      'Exhaust fans — {qty} fan(s)'),
    laborItem('p14-circuit', 'Appliance Circuits', 'Appliance circuits', 'circuit', 3, LABOR,
      'Dedicated circuits for range, dryer, EV charger.',
      'Appliance circuits — {qty} circuit(s)', true, 'Licensed electrician required'),
    laborItem('p14-smart', 'Smart Switch / Dimmer', 'Smart switches', 'device', 0.75, LABOR,
      'Smart switch and dimmer installation.',
      'Smart switches/dimmers — {qty} device(s)'),
    laborItem('p14-doorbell', 'Doorbell / Camera Rough-In', 'Doorbell/camera', 'unit', 1.5, LABOR,
      'Doorbell and security camera rough-in.',
      'Doorbell/camera rough-in — {qty} location(s)'),
  ],
};

// ─── PHASE 15: PAINTING ───────────────────────────────────────
const phase15: PhaseGroup = {
  id: 15, name: 'Painting', icon: '🎨',
  description: 'Interior and exterior painting — walls, ceilings, trim, cabinets, decks, and fences — prep, prime, and finish coats.',
  items: [
    matItem('p15-int-wall', 'Interior Walls', 'Interior walls', 'sqft',
      tiers(0.35,'1-coat paint','Primer + 1 finish coat', 0.55,'2-coat paint','Primer + 2 finish coats', 0.80,'Premium paint','Sherwin-Williams Emerald 2-coat'),
      0.008, LABOR,
      'Interior wall painting — prep, prime, and finish coats.',
      'Interior walls — {qty} sq ft ({tier} grade)', 0, false),
    matItem('p15-ceiling', 'Interior Ceilings', 'Interior ceilings', 'sqft',
      tiers(0.30,'1-coat ceiling paint','Primer + 1 coat flat', 0.45,'2-coat ceiling paint','Primer + 2 coats flat', 0.65,'Premium ceiling paint','Sherwin-Williams 2-coat'),
      0.006, LABOR,
      'Interior ceiling painting.',
      'Interior ceilings — {qty} sq ft ({tier} grade)', 0),
    matItem('p15-trim', 'Interior Trim & Doors — Paint', 'Trim & door paint', 'lf',
      tiers(0.45,'1-coat trim paint','Brush + 1 coat semi-gloss', 0.70,'2-coat trim paint','Sand + 2 coats semi-gloss', 1.10,'Spray finish trim','Spray-applied semi-gloss'),
      0.010, LABOR,
      'Interior trim and door painting.',
      'Interior trim/doors — {qty} lf ({tier} grade)', 0, false),
    matItem('p15-cab', 'Cabinet Painting', 'Cabinet painting', 'box',
      tiers(55,'Brush/roll cabinet paint','Brush-applied cabinet paint', 85,'Spray cabinet paint','Spray-applied finish', 140,'Premium spray finish','Fine finish spray + primer'),
      3, LABOR,
      'Cabinet painting — spray finish.',
      'Cabinet painting — {qty} door/box ({tier} grade)', 0),
    matItem('p15-ext-wall', 'Exterior Walls / Siding', 'Exterior paint', 'sqft',
      tiers(0.40,'1-coat exterior paint','Primer + 1 finish coat', 0.65,'2-coat exterior paint','Primer + 2 finish coats', 0.95,'Premium exterior paint','Sherwin-Williams Duration 2-coat'),
      0.008, LABOR,
      'Exterior wall and siding painting.',
      'Exterior walls/siding — {qty} sq ft ({tier} grade)', 0),
    matItem('p15-ext-trim', 'Exterior Trim, Fascia, Soffits', 'Exterior trim paint', 'lf',
      tiers(0.50,'1-coat exterior trim','Brush + 1 coat', 0.80,'2-coat exterior trim','Sand + 2 coats', 1.20,'Premium exterior trim','Spray + 2 coats'),
      0.010, LABOR,
      'Exterior trim, fascia, and soffit painting.',
      'Exterior trim/fascia — {qty} lf ({tier} grade)', 0),
    matItem('p15-deck', 'Deck Stain / Paint', 'Deck stain', 'sqft',
      tiers(0.35,'Solid deck stain','1-coat solid stain', 0.55,'Premium solid stain','2-coat solid stain', 0.80,'Deck paint system','Primer + 2 coats deck paint'),
      0.006, LABOR,
      'Deck staining or painting.',
      'Deck stain/paint — {qty} sq ft ({tier} grade)', 0),
    matItem('p15-fence', 'Fence Stain / Paint', 'Fence stain', 'lf',
      tiers(0.40,'Solid fence stain','1-coat solid stain', 0.65,'Premium fence stain','2-coat solid stain', 0.90,'Fence paint','Primer + 2 coats'),
      0.006, LABOR,
      'Fence staining or painting.',
      'Fence stain/paint — {qty} lf ({tier} grade)', 0),
    matItem('p15-epoxy', 'Epoxy Floor Coating (Garage)', 'Epoxy floor', 'sqft',
      tiers(1.80,'Single-layer epoxy','Standard epoxy coating', 3.00,'2-layer epoxy','Base + topcoat epoxy', 5.00,'Polyaspartic coating','Premium polyaspartic system'),
      0.012, LABOR,
      'Garage floor epoxy coating.',
      'Epoxy floor coating — {qty} sq ft ({tier} grade)', 5),
  ],
};

// ─── PHASE 16: APPLIANCES & SPECIALTIES ───────────────────────
const phase16: PhaseGroup = {
  id: 16, name: 'Appliances & Specialties', icon: '🔌',
  description: 'Appliance installation, specialty items, and finishing touches including range hoods, fireplaces, and window treatments.',
  items: [
    laborItem('p16-appliance', 'Appliance Install (Range, Fridge, DW, Microwave)', 'Appliance install', 'unit', 1.5, LABOR,
      'Appliance installation and hookup.',
      'Appliance install — {qty} unit(s)'),
    laborItem('p16-hood', 'Hood Vent Install', 'Hood vent', 'unit', 3, LABOR,
      'Range hood vent installation.',
      'Hood vent — {qty} unit(s)'),
    laborItem('p16-fireplace', 'Fireplace Gas Insert', 'Gas fireplace', 'unit', 6, LABOR,
      'Gas fireplace insert installation.',
      'Gas fireplace insert — {qty} unit(s)', true, 'Sub specialty — gas contractor required'),
    laborItem('p16-bath-acc', 'Bathroom Accessories', 'Bath accessories', 'unit', 0.5, LABOR,
      'Towel bars, TP holders, mirrors, and accessories.',
      'Bathroom accessories — {qty} piece(s)'),
    laborItem('p16-blinds', 'Window Treatments / Blinds', 'Window treatments', 'window', 0.75, LABOR,
      'Window blind and treatment installation.',
      'Window treatments — {qty} window(s)'),
  ],
};

// ─── PHASE 17: FINAL CLEANING & CLOSEOUT ──────────────────────
const phase17: PhaseGroup = {
  id: 17, name: 'Final Cleaning & Closeout', icon: '✅',
  description: 'Post-construction cleaning, exterior site cleanup, punch list completion, and final walkthrough with client sign-off.',
  items: [
    laborItem('p17-clean', 'Post-Construction Clean — Interior', 'Post-construction clean', 'sqft', 0.004, LABOR,
      'Final interior post-construction cleaning.',
      'Post-construction clean — {qty} sq ft'),
    laborItem('p17-windows', 'Window Cleaning — Post-Construction', 'Window cleaning', 'window', 0.5, LABOR,
      'Post-construction window cleaning.',
      'Window cleaning — {qty} window(s)'),
    laborItem('p17-ext-clean', 'Exterior Site Cleanup', 'Exterior cleanup', 'hr', 1, LABOR,
      'Exterior site cleanup and debris removal.',
      'Exterior site cleanup — {qty} hrs'),
    laborItem('p17-punch', 'Touch-Up Punch List', 'Punch list', 'hr', 1, LABOR,
      'Final touch-up and punch list completion.',
      'Touch-up punch list — {qty} hrs'),
    laborItem('p17-walkthrough', 'Final Walkthrough / Sign-Off', 'Final walkthrough', 'hr', 1, LABOR,
      'Final walkthrough and sign-off documentation.',
      'Final walkthrough — {qty} hrs'),
  ],
};

// ─── EXPORT ALL PHASES ────────────────────────────────────────
export const ALL_PHASES: PhaseGroup[] = [
  phase1, phase2, phase3, phase4, phase5,
  phase6, phase7, phase8, phase9, phase10,
  phase11, phase12, phase13, phase14, phase15,
  phase16, phase17,
];

export const DEFAULTS = {
  markupPct: 0.40,
  laborRate: LABOR,
  paintRate: PAINT,
};
