CREATE TABLE `customerAddresses` (
	`id` varchar(64) NOT NULL,
	`customerId` varchar(64) NOT NULL,
	`label` varchar(64) NOT NULL DEFAULT 'Home',
	`street` varchar(255) NOT NULL DEFAULT '',
	`unit` varchar(64) NOT NULL DEFAULT '',
	`city` varchar(128) NOT NULL DEFAULT '',
	`state` varchar(64) NOT NULL DEFAULT '',
	`zip` varchar(10) NOT NULL DEFAULT '',
	`isPrimary` boolean NOT NULL DEFAULT false,
	`lat` text,
	`lng` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `customerAddresses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customers` (
	`id` varchar(64) NOT NULL,
	`firstName` varchar(128) NOT NULL DEFAULT '',
	`lastName` varchar(128) NOT NULL DEFAULT '',
	`displayName` varchar(255) NOT NULL DEFAULT '',
	`company` varchar(255) NOT NULL DEFAULT '',
	`mobilePhone` varchar(32) NOT NULL DEFAULT '',
	`homePhone` varchar(32) NOT NULL DEFAULT '',
	`workPhone` varchar(32) NOT NULL DEFAULT '',
	`email` varchar(320) NOT NULL DEFAULT '',
	`role` varchar(128) NOT NULL DEFAULT '',
	`customerType` varchar(32) NOT NULL DEFAULT 'homeowner',
	`doNotService` boolean NOT NULL DEFAULT false,
	`street` varchar(255) NOT NULL DEFAULT '',
	`unit` varchar(64) NOT NULL DEFAULT '',
	`city` varchar(128) NOT NULL DEFAULT '',
	`state` varchar(64) NOT NULL DEFAULT '',
	`zip` varchar(10) NOT NULL DEFAULT '',
	`addressNotes` text,
	`customerNotes` text,
	`billsTo` varchar(255) NOT NULL DEFAULT '',
	`tags` text,
	`leadSource` varchar(64) NOT NULL DEFAULT '',
	`referredBy` varchar(255) NOT NULL DEFAULT '',
	`sendNotifications` boolean NOT NULL DEFAULT true,
	`sendMarketingOptIn` boolean NOT NULL DEFAULT false,
	`defaultTaxCode` varchar(16),
	`lifetimeValue` int NOT NULL DEFAULT 0,
	`outstandingBalance` int NOT NULL DEFAULT 0,
	`onlineRequestId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `opportunities` (
	`id` varchar(64) NOT NULL,
	`customerId` varchar(64) NOT NULL,
	`area` varchar(16) NOT NULL DEFAULT 'lead',
	`stage` varchar(64) NOT NULL DEFAULT 'New Lead',
	`title` varchar(255) NOT NULL DEFAULT '',
	`value` int NOT NULL DEFAULT 0,
	`jobNumber` varchar(64),
	`notes` text,
	`archived` boolean NOT NULL DEFAULT false,
	`archivedAt` varchar(32),
	`sourceLeadId` varchar(64),
	`sourceEstimateId` varchar(64),
	`convertedToEstimateAt` varchar(32),
	`convertedToJobAt` varchar(32),
	`sentAt` varchar(32),
	`wonAt` varchar(32),
	`scheduledDate` varchar(32),
	`scheduledEndDate` varchar(32),
	`scheduledDuration` int,
	`assignedTo` text,
	`scheduleNotes` text,
	`estimateSnapshot` text,
	`tasks` text,
	`attachments` text,
	`jobActivity` text,
	`clientSnapshot` text,
	`signedEstimateUrl` text,
	`signedEstimateFilename` varchar(255),
	`completionSignatureUrl` text,
	`completionSignedBy` varchar(255),
	`completionSignedAt` varchar(32),
	`sowDocument` text,
	`sowGeneratedAt` varchar(32),
	`onlineRequestId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `opportunities_id` PRIMARY KEY(`id`)
);
