/**
 * /admin/marketing/reengagement-campaign
 *
 * Operator console for the database reactivation campaign.
 *
 * Workflow:
 *   1. (One-time) Click "New campaign" or pick an existing one.
 *   2. Click "Segment preview" to see HOT/WARM/COLD counts against the cohort.
 *   3. Click "Generate 20 HOT pilot drafts" — Claude writes both email + SMS
 *      per customer, drafts land in `pending` status.
 *   4. Review each card: edit subject/body, then Approve / Reject.
 *      Bulk-approve a segment with one click when tone is right.
 *   5. The send worker (cron, every 5 min) drains approved drafts at
 *      50 emails/day + 25 SMS/day. Replies surface via Email Manager AI.
 */
import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Spinner } from "@/components/ui/spinner";
import AdminAccessDenied from "@/pages/AdminAccessDenied";
import { toast } from "sonner";

type Segment = "hot" | "warm" | "cold";

const SEGMENT_LABELS: Record<Segment, string> = {
  hot: "HOT — last work ≤ 6 mo",
  warm: "WARM — 6–24 mo",
  cold: "COLD — 24+ mo",
};

const SEGMENT_DESC: Record<Segment, string> = {
  hot: "Subject pattern: \"A short note on your recent project\". Light check-in, complimentary return visit if needed. No pitch.",
  warm: "Subject pattern: \"A standard-of-care look at your home\". Offer complimentary 360° Roadmap walk-through. Soft membership intro.",
  cold: "Subject pattern: \"An overdue hello\". Friendly relationship reset, no pitch.",
};

const STATUS_COLORS: Record<string, string> = {
  pending: "bg-amber-100 text-amber-800 border-amber-300",
  approved: "bg-emerald-100 text-emerald-800 border-emerald-300",
  rejected: "bg-rose-100 text-rose-800 border-rose-300",
  queued: "bg-blue-100 text-blue-800 border-blue-300",
  sent: "bg-emerald-200 text-emerald-900 border-emerald-400",
  bounced: "bg-rose-200 text-rose-900 border-rose-400",
  replied: "bg-violet-100 text-violet-800 border-violet-300",
  failed: "bg-rose-200 text-rose-900 border-rose-400",
};

export default function ReengagementCampaignPage() {
  const { user, loading } = useAuth();

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Spinner />
      </div>
    );
  }
  if (!user) {
    window.location.href = "/";
    return null;
  }
  if (user.role !== "admin") {
    return <AdminAccessDenied email={user.email} />;
  }
  return <Console />;
}

function Console() {
  const utils = trpc.useUtils();
  const campaignsQuery = trpc.reengagement.listCampaigns.useQuery();
  const [activeCampaignId, setActiveCampaignId] = useState<number | null>(null);

  // Default to the most recent campaign
  useEffect(() => {
    if (activeCampaignId === null && campaignsQuery.data && campaignsQuery.data.length > 0) {
      setActiveCampaignId(campaignsQuery.data[0].id);
    }
  }, [activeCampaignId, campaignsQuery.data]);

  const createCampaign = trpc.reengagement.createCampaign.useMutation({
    onSuccess: (row) => {
      toast.success(`Campaign "${row?.name}" created`);
      campaignsQuery.refetch();
      if (row?.id) setActiveCampaignId(row.id);
    },
    onError: (err) => toast.error(err.message),
  });

  const onCreate = () => {
    const name = window.prompt(
      "Campaign name",
      `HCP Reactivation — ${new Date().toISOString().slice(0, 10)}`,
    );
    if (!name) return;
    createCampaign.mutate({ name, segment: "custom" });
  };

  return (
    <div className="min-h-screen bg-background p-6">
      <div className="max-w-7xl mx-auto space-y-6">
        <header className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">Re-engagement Campaign</h1>
            <p className="text-sm text-muted-foreground">
              Personalized email + SMS drafts for past customers, generated by Claude, reviewed by you, sent at 50 email + 25 SMS per day.
            </p>
          </div>
          <div className="flex items-center gap-3">
            <select
              className="h-9 rounded-md border border-input bg-background px-3 text-sm"
              value={activeCampaignId ?? ""}
              onChange={(e) =>
                setActiveCampaignId(e.target.value ? Number(e.target.value) : null)
              }
            >
              <option value="">— select campaign —</option>
              {campaignsQuery.data?.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.name} ({c.status})
                </option>
              ))}
            </select>
            <Button onClick={onCreate} disabled={createCampaign.isPending}>
              + New campaign
            </Button>
          </div>
        </header>

        {activeCampaignId ? (
          <CampaignBoard campaignId={activeCampaignId} />
        ) : (
          <Card>
            <CardContent className="py-10 text-center text-muted-foreground">
              Create a campaign to start. The first one is typically named
              "HCP Reactivation — {new Date().toISOString().slice(0, 10)}".
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}

function CampaignBoard({ campaignId }: { campaignId: number }) {
  const utils = trpc.useUtils();
  const statsQuery = trpc.reengagement.stats.useQuery({ campaignId });
  const [activeSegment, setActiveSegment] = useState<Segment>("hot");
  const draftsQuery = trpc.reengagement.listDrafts.useQuery({
    campaignId,
    segment: activeSegment,
    limit: 200,
  });

  // Pilot generation
  const generatePilot = trpc.reengagement.generatePilot.useMutation({
    onSuccess: (r) => {
      toast.success(
        `Generated ${r.generated} drafts (${r.skipped.length} skipped, ${r.errors.length} errors). Cohort size: ${r.cohortSize}.`,
      );
      draftsQuery.refetch();
      statsQuery.refetch();
    },
    onError: (err) => toast.error(err.message),
  });

  // Bulk approve
  const bulkApprove = trpc.reengagement.bulkApproveSegment.useMutation({
    onSuccess: () => {
      toast.success(`Approved all pending ${activeSegment.toUpperCase()} drafts`);
      draftsQuery.refetch();
      statsQuery.refetch();
    },
    onError: (err) => toast.error(err.message),
  });

  const segmentPreview = trpc.reengagement.segmentPreview.useQuery(
    { leadSourceLike: undefined },
    { enabled: false },
  );
  const [previewOpen, setPreviewOpen] = useState(false);

  const onPreview = async () => {
    setPreviewOpen(true);
    if (!segmentPreview.data) await segmentPreview.refetch();
  };

  return (
    <div className="space-y-6">
      <StatsStrip campaignId={campaignId} stats={statsQuery.data ?? []} />

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base">Pilot</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-wrap items-center gap-3">
          <Button
            onClick={() =>
              generatePilot.mutate({
                campaignId,
                segment: "hot",
                limit: 20,
              })
            }
            disabled={generatePilot.isPending}
          >
            {generatePilot.isPending && generatePilot.variables?.segment === "hot"
              ? "Generating…"
              : "Generate 20 HOT pilot drafts"}
          </Button>
          <Button
            variant="outline"
            onClick={() =>
              generatePilot.mutate({
                campaignId,
                segment: "warm",
                limit: 20,
              })
            }
            disabled={generatePilot.isPending}
          >
            Generate 20 WARM
          </Button>
          <Button
            variant="outline"
            onClick={() =>
              generatePilot.mutate({
                campaignId,
                segment: "cold",
                limit: 20,
              })
            }
            disabled={generatePilot.isPending}
          >
            Generate 20 COLD
          </Button>
          <Button variant="ghost" onClick={onPreview}>
            Segment preview
          </Button>
          <p className="ml-auto text-xs text-muted-foreground max-w-md">
            Pilot first. Review tone before scaling. Each pilot run uses ~20 Claude
            Opus calls.
          </p>
        </CardContent>
      </Card>

      <Tabs value={activeSegment} onValueChange={(v) => setActiveSegment(v as Segment)}>
        <TabsList>
          {(["hot", "warm", "cold"] as Segment[]).map((s) => (
            <TabsTrigger key={s} value={s}>
              {SEGMENT_LABELS[s]}
            </TabsTrigger>
          ))}
        </TabsList>

        {(["hot", "warm", "cold"] as Segment[]).map((s) => (
          <TabsContent key={s} value={s} className="space-y-4">
            <Card>
              <CardContent className="py-4 flex flex-wrap items-center gap-3">
                <p className="text-sm text-muted-foreground flex-1">
                  {SEGMENT_DESC[s]}
                </p>
                <Button
                  variant="default"
                  onClick={() =>
                    bulkApprove.mutate({ campaignId, segment: s })
                  }
                  disabled={bulkApprove.isPending}
                >
                  Approve all pending in this segment
                </Button>
              </CardContent>
            </Card>

            {draftsQuery.isLoading ? (
              <div className="py-10 text-center text-muted-foreground">
                <Spinner />
              </div>
            ) : !draftsQuery.data || draftsQuery.data.length === 0 ? (
              <Card>
                <CardContent className="py-10 text-center text-muted-foreground">
                  No {s.toUpperCase()} drafts yet. Generate a pilot batch above.
                </CardContent>
              </Card>
            ) : (
              <DraftList
                drafts={draftsQuery.data}
                onChange={() => {
                  draftsQuery.refetch();
                  statsQuery.refetch();
                }}
              />
            )}
          </TabsContent>
        ))}
      </Tabs>

      <SegmentPreviewDialog
        open={previewOpen}
        onOpenChange={setPreviewOpen}
        data={segmentPreview.data}
        loading={segmentPreview.isFetching}
      />
    </div>
  );
}

// ── Stats strip ─────────────────────────────────────────────────────────────
function StatsStrip({
  campaignId,
  stats,
}: {
  campaignId: number;
  stats: Array<{ segment: string; channel: string; status: string; n: number }>;
}) {
  // Aggregate counts
  const total = stats.reduce((acc, r) => acc + r.n, 0);
  const byStatus: Record<string, number> = {};
  for (const r of stats) byStatus[r.status] = (byStatus[r.status] ?? 0) + r.n;

  const cells: { label: string; value: number; key: string }[] = [
    { label: "Drafted", value: total, key: "total" },
    { label: "Approved", value: byStatus.approved ?? 0, key: "approved" },
    { label: "Sent", value: byStatus.sent ?? 0, key: "sent" },
    { label: "Replied", value: byStatus.replied ?? 0, key: "replied" },
    { label: "Bounced", value: byStatus.bounced ?? 0, key: "bounced" },
    { label: "Failed", value: byStatus.failed ?? 0, key: "failed" },
  ];

  return (
    <div className="grid grid-cols-2 md:grid-cols-6 gap-3">
      {cells.map((c) => (
        <Card key={c.key}>
          <CardContent className="py-4 text-center">
            <div className="text-2xl font-semibold">{c.value}</div>
            <div className="text-xs uppercase tracking-wide text-muted-foreground">
              {c.label}
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}

// ── Draft cards ─────────────────────────────────────────────────────────────
type DraftRow = {
  id: number;
  campaignId: number;
  customerId: string;
  segment: string;
  channel: string;
  subject: string | null;
  body: string;
  status: string;
  customerHistorySummary: string | null;
  qaNotes: string | null;
  lastWorkDate: string | null;
  lastWorkSummary: string | null;
  lifetimeValueCents: number | null;
  sentAt: Date | null;
  createdAt: Date;
};

function DraftList({
  drafts,
  onChange,
}: {
  drafts: DraftRow[];
  onChange: () => void;
}) {
  // Group by customerId so email + sms for the same customer render together
  const grouped = useMemo(() => {
    const map = new Map<string, DraftRow[]>();
    for (const d of drafts) {
      const arr = map.get(d.customerId) ?? [];
      arr.push(d);
      map.set(d.customerId, arr);
    }
    return Array.from(map.entries());
  }, [drafts]);

  return (
    <div className="space-y-4">
      {grouped.map(([customerId, rows]) => (
        <CustomerDraftCard
          key={customerId}
          customerId={customerId}
          drafts={rows}
          onChange={onChange}
        />
      ))}
    </div>
  );
}

function CustomerDraftCard({
  customerId,
  drafts,
  onChange,
}: {
  customerId: string;
  drafts: DraftRow[];
  onChange: () => void;
}) {
  const customerHistory = trpc.reengagement.customerHistory.useQuery({ customerId });
  const summary = drafts[0]?.customerHistorySummary;
  const lastWorkDate = drafts[0]?.lastWorkDate;
  const lastWorkSummary = drafts[0]?.lastWorkSummary;
  const ltvDollars = drafts[0]?.lifetimeValueCents
    ? Math.round((drafts[0].lifetimeValueCents ?? 0) / 100)
    : 0;
  const customerName =
    customerHistory.data && !("skipped" in customerHistory.data)
      ? `${customerHistory.data.firstName} ${customerHistory.data.lastName}`.trim()
      : "(loading)";

  return (
    <Card>
      <CardHeader className="pb-2">
        <div className="flex items-start justify-between gap-3">
          <div>
            <CardTitle className="text-base">
              {customerName || "(no name)"}
            </CardTitle>
            <p className="text-xs text-muted-foreground mt-1">
              Last work: {lastWorkDate ?? "(none on file)"} ·
              {" "}
              {lastWorkSummary ? `"${truncate(lastWorkSummary, 100)}"` : "no description"}
              {ltvDollars > 0 ? ` · LTV $${ltvDollars.toLocaleString()}` : ""}
            </p>
          </div>
        </div>
        {summary && (
          <p className="text-xs italic text-muted-foreground border-l-2 border-muted pl-2 mt-2">
            {summary}
          </p>
        )}
      </CardHeader>
      <CardContent className="space-y-4">
        {drafts.map((d) => (
          <DraftRow key={d.id} draft={d} onChange={onChange} />
        ))}
      </CardContent>
    </Card>
  );
}

function DraftRow({ draft, onChange }: { draft: DraftRow; onChange: () => void }) {
  const [isEditing, setIsEditing] = useState(false);
  const [subject, setSubject] = useState(draft.subject ?? "");
  const [body, setBody] = useState(draft.body);

  const update = trpc.reengagement.updateDraft.useMutation({
    onSuccess: () => {
      toast.success("Saved");
      setIsEditing(false);
      onChange();
    },
    onError: (e) => toast.error(e.message),
  });
  const approve = trpc.reengagement.approveDraft.useMutation({
    onSuccess: () => {
      toast.success("Approved");
      onChange();
    },
    onError: (e) => toast.error(e.message),
  });
  const reject = trpc.reengagement.rejectDraft.useMutation({
    onSuccess: () => {
      toast.success("Rejected");
      onChange();
    },
    onError: (e) => toast.error(e.message),
  });
  const sendTest = trpc.reengagement.sendTestEmail.useMutation({
    onSuccess: () => toast.success("Test email sent"),
    onError: (e) => toast.error(e.message),
  });

  const onTest = () => {
    const to = window.prompt("Send test email to address:", "help@handypioneers.com");
    if (!to) return;
    sendTest.mutate({ draftId: draft.id, toEmail: to });
  };

  const isImmutable = ["sent", "queued"].includes(draft.status);

  return (
    <div className="border rounded-md p-3 space-y-2 bg-muted/20">
      <div className="flex items-center gap-2">
        <Badge variant="outline" className="uppercase">
          {draft.channel}
        </Badge>
        <Badge variant="outline" className={STATUS_COLORS[draft.status] ?? ""}>
          {draft.status}
        </Badge>
        <Badge variant="outline" className="uppercase">
          {draft.segment}
        </Badge>
        <span className="text-xs text-muted-foreground ml-auto">
          {new Date(draft.createdAt).toLocaleString()}
        </span>
      </div>

      {isEditing ? (
        <>
          {draft.channel === "email" && (
            <Input
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              placeholder="Subject"
              className="font-medium"
            />
          )}
          <Textarea
            value={body}
            onChange={(e) => setBody(e.target.value)}
            rows={draft.channel === "email" ? 8 : 3}
          />
          <div className="flex gap-2">
            <Button
              size="sm"
              onClick={() =>
                update.mutate({
                  id: draft.id,
                  subject: draft.channel === "email" ? subject : undefined,
                  body,
                })
              }
              disabled={update.isPending}
            >
              Save
            </Button>
            <Button
              size="sm"
              variant="ghost"
              onClick={() => {
                setSubject(draft.subject ?? "");
                setBody(draft.body);
                setIsEditing(false);
              }}
            >
              Cancel
            </Button>
          </div>
        </>
      ) : (
        <>
          {draft.channel === "email" && draft.subject && (
            <div className="font-medium text-sm">{draft.subject}</div>
          )}
          <pre className="whitespace-pre-wrap text-sm font-sans">{draft.body}</pre>
          {draft.qaNotes && (
            <details className="text-xs text-muted-foreground">
              <summary className="cursor-pointer">Self-audit notes</summary>
              <p className="mt-1">{draft.qaNotes}</p>
            </details>
          )}
          {!isImmutable && (
            <div className="flex gap-2 flex-wrap">
              <Button size="sm" variant="outline" onClick={() => setIsEditing(true)}>
                Edit
              </Button>
              {draft.status === "pending" && (
                <>
                  <Button
                    size="sm"
                    onClick={() => approve.mutate({ id: draft.id })}
                    disabled={approve.isPending}
                  >
                    Approve
                  </Button>
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={() => reject.mutate({ id: draft.id })}
                    disabled={reject.isPending}
                  >
                    Reject
                  </Button>
                </>
              )}
              {draft.channel === "email" && (
                <Button size="sm" variant="ghost" onClick={onTest}>
                  Send test
                </Button>
              )}
            </div>
          )}
        </>
      )}
    </div>
  );
}

// ── Segment preview dialog ──────────────────────────────────────────────────
function SegmentPreviewDialog({
  open,
  onOpenChange,
  data,
  loading,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  data:
    | {
        counts: { hot: number; warm: number; cold: number; skipped: number };
        skippedReasons: Record<string, number>;
        sample: Record<string, Array<{ customerId: string; name: string; email: string; phone: string; lastWorkDate: string | null; lastWorkSummary: string }>>;
      }
    | undefined;
  loading: boolean;
}) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Segmentation preview</DialogTitle>
        </DialogHeader>
        {loading || !data ? (
          <div className="py-10 text-center"><Spinner /></div>
        ) : (
          <div className="space-y-4">
            <div className="grid grid-cols-4 gap-3">
              {(["hot", "warm", "cold"] as Segment[]).map((s) => (
                <div key={s} className="border rounded p-3 text-center">
                  <div className="text-xs uppercase text-muted-foreground">{s}</div>
                  <div className="text-2xl font-semibold">{data.counts[s]}</div>
                </div>
              ))}
              <div className="border rounded p-3 text-center">
                <div className="text-xs uppercase text-muted-foreground">Skipped</div>
                <div className="text-2xl font-semibold">{data.counts.skipped}</div>
              </div>
            </div>
            <div className="text-xs text-muted-foreground">
              Skip reasons:{" "}
              {Object.entries(data.skippedReasons)
                .map(([r, n]) => `${r}: ${n}`)
                .join(" · ") || "(none)"}
            </div>
            {(["hot", "warm", "cold"] as Segment[]).map((s) => (
              <details key={s}>
                <summary className="cursor-pointer text-sm font-medium uppercase">
                  {s} sample (first 50)
                </summary>
                <ul className="text-xs mt-1 space-y-1">
                  {data.sample[s]?.map((c) => (
                    <li key={c.customerId} className="border-b py-1">
                      <span className="font-medium">{c.name}</span> · {c.email || c.phone || "(no contact)"} · last: {c.lastWorkDate ?? "—"} · {truncate(c.lastWorkSummary, 80)}
                    </li>
                  ))}
                </ul>
              </details>
            ))}
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

function truncate(s: string, n: number): string {
  if (!s) return "";
  return s.length <= n ? s : s.slice(0, n - 1) + "…";
}
